# Generated by Django 5.2.5 on 2025-08-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='previous_incidents',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='reporter_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='reporter_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='reporter_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='support_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='witness_present',
            field=models.BooleanField(default=False),
        ),
    ]
