# Generated by Django 5.2.5 on 2025-09-07 08:17

import tccweb.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_populate_and_constrain_tracking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='tracking_code',
            field=models.CharField(default=tccweb.core.models.generate_tracking_code, editable=False, max_length=12, unique=True),
        ),
    ]
