# Generated by Django 5.2.5 on 2025-08-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_report_assigned_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("under_review", "Under Review"),
                    ("resolved", "Resolved"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]