# Generated by Django 5.2.5 on 2025-09-13 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='educationalresource',
            new_name='core_educat_created_4c8b96_idx',
            old_name='core_res_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='educationalresource',
            new_name='core_educat_created_9798ec_idx',
            old_name='core_res_created_by_idx',
        ),
        migrations.RenameIndex(
            model_name='quiz',
            new_name='core_quiz_created_e686bf_idx',
            old_name='core_quiz_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='quiz',
            new_name='core_quiz_created_4fb56a_idx',
            old_name='core_quiz_created_by_idx',
        ),
        migrations.RenameIndex(
            model_name='quizquestion',
            new_name='core_quizqu_quiz_id_f9ddd7_idx',
            old_name='core_question_quiz_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='core_report_created_9527e7_idx',
            old_name='core_report_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='core_report_status_4c7c3f_idx',
            old_name='core_report_status_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='core_report_reporte_b73a39_idx',
            old_name='core_report_reporter_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='core_report_assigne_06da45_idx',
            old_name='core_report_assigned_to_idx',
        ),
        migrations.RenameIndex(
            model_name='supportcontact',
            new_name='core_suppor_created_862716_idx',
            old_name='core_support_created_at_idx',
        ),
    ]
