# Generated by Django 5.2.5 on 2025-11-03 09:22

import django.core.files.storage
import django.core.validators
import pathlib
import tccweb.core.models
import tccweb.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_core_res_created_at_idx_core_educat_created_4c8b96_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalresource',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/Users/abs/Desktop/tccweb/tccweb/protected_media')), upload_to=tccweb.core.models.resource_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'mp4']), tccweb.core.validators.validate_file_type, tccweb.core.models.validate_file_size, tccweb.core.validators.validate_no_malware]),
        ),
    ]
