# Generated by Django 5.2.5 on 2025-11-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_report_timeline_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='report',
            new_name='core_report_assigne_cfb8e5_idx',
            old_name='core_report_assigned_at_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='core_report_resolve_535e31_idx',
            old_name='core_report_resolved_at_idx',
        ),
    ]
