# Generated by Django 5.2.5 on 2025-11-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_core_report_assigned_at_idx_core_report_assigne_cfb8e5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='awaiting_response',
            field=models.BooleanField(default=True, help_text='Whether the next action is expected from the assigned counselor.'),
        ),
    ]
