# Generated by Django 5.2.5 on 2025-11-11 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_systemlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='systemlog',
            new_name='core_system_user_id_593cbc_idx',
            old_name='systemlog_user_timestamp_idx',
        ),
    ]
