# Generated by Django 5.2.5 on 2025-11-12 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_systemlog_user_timestamp_idx_core_system_user_id_593cbc_idx'),
        ('core', '0013_securitylog'),
    ]

    operations = [
    ]
