# Generated by Django 5.2.5 on 2025-11-12 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_20251112_1010'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='systemlog',
            new_name='systemlog_user_timestamp_idx',
            old_name='core_system_user_id_593cbc_idx',
        ),
    ]
