# Generated by Django 5.2.5 on 2025-09-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor_portal', '0003_chatmessage_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
