# Generated by Django 5.2.5 on 2025-09-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselor_portal', '0004_admin_alerts'),
        ('counselor_portal', '0004_alter_chatmessage_is_read'),
    ]

    operations = [
    ]
