# Generated by Django 5.2.5 on 2025-09-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselor_portal', '0005_merge_20250912_1656'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminAlert',
        ),
    ]
