# Generated by Django 5.2.5 on 2025-09-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselor_portal', '0005_end_to_end_encryption'),
        ('counselor_portal', '0006_delete_adminalert'),
    ]

    operations = [
    ]
