# Generated by Django 5.2.5 on 2025-09-13 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselor_portal', '0002_add_indexes'),
        ('counselor_portal', '0008_alter_chatmessage_cipher_for_recipient_and_more'),
    ]

    operations = [
    ]
