# Generated by Django 5.2.5 on 2025-09-13 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselor_portal', '0009_merge_20250913_1254'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='casenote',
            new_name='counselor_p_created_f19058_idx',
            old_name='counselor_note_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='casenote',
            new_name='counselor_p_report__0140a5_idx',
            old_name='counselor_note_report_idx',
        ),
        migrations.RenameIndex(
            model_name='casenote',
            new_name='counselor_p_counsel_9b3e91_idx',
            old_name='counselor_note_counselor_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='counselor_p_timesta_2d6212_idx',
            old_name='counselor_msg_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='counselor_p_report__3fca83_idx',
            old_name='counselor_msg_report_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='counselor_p_sender__9bc3f6_idx',
            old_name='counselor_msg_sender_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='counselor_p_recipie_1005d9_idx',
            old_name='counselor_msg_recipient_idx',
        ),
    ]
