# Generated by Django 5.2.5 on 2025-09-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor_portal', '0011_adminalert_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adminalert',
            new_name='adm_alert_created_idx',
            old_name='counselor_p_adminal_created_idx',
        ),
        migrations.RenameIndex(
            model_name='adminalert',
            new_name='adm_alert_admin_idx',
            old_name='counselor_p_adminal_admin_idx',
        ),
        migrations.RenameIndex(
            model_name='adminalert',
            new_name='adm_alert_report_idx',
            old_name='counselor_p_adminal_report_idx',
        ),
        migrations.AlterField(
            model_name='adminalert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
