# Generated by Django 5.2.5 on 2025-11-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor_portal', '0014_counselorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselorprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
