# Generated by Django 5.2.5 on 2025-11-08 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselor_portal', '0015_alter_counselorprofile_id'),
        ('counselor_portal', '0015_chatmessage_emotion_fields'),
    ]

    operations = [
    ]
