# Generated by Django 5.2.5 on 2025-11-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor_portal', '0018_alter_collaborationmessage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborationmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
