# Generated by Django 5.2.5 on 2025-11-17 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselor_portal', '0019_alter_collaborationmessage_id'),
        ('counselor_portal', '0019_ensure_case_note_schema'),
    ]

    operations = [
    ]
